### ISSUE TITLE
UI localization support

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#10]
All texts in UI should be defined in some file and we need the ability to pass a custom file.

**Comment by Menelion** [comment]
Ideally, this should be a mature localization solution supporting also date formatting, HTML `lang` attribute changing and all the nitty-gritty stuff.

[This](https://github.com/synacor/preact-i18n) seems to be quite a good solution for Preact.  
The dates can be formatted with [Luxon](https://github.com/moment/luxon), for example.

**Comment by umputun** [comment]
dates look ... unusual to me. For example `13.05.18 at 11:32` will be very confusing to anyone living with MM-DD-YY standard

**Comment by Menelion** [comment]
`DateTime.local().setLocale('en-US').toLocaleString()`? :) Anyway, @igoradamenko, what do you think of all this?

**Comment by igoradamenko** [comment]
I understand that current date format may be unusual for people from Europe, USA, etc. I used the most popular format in my country, but with English. I did it in this way, because i18n is complicated on the first steps and we had a lot of things to do. And because first Remark42 users are from Russia, Ukraine and other Russian speaking countries.

`DateTime` is a part of Intl API, [which isn't supported in iOS Safari < 10](https://caniuse.com/#feat=internationalization). It's not a big problem, but it means that we need to remember about fallbacks and other stuff like this.

BTW, I wanted to add time format like `5 minutes ago` and similar, because it's more useful than regular date. But the regular date can be inside `title` attribute, because sometimes users want to get exact date. And it may be in format that user has used to see, sure.

So, yeah, we will improve i18n for dates :-)

**Comment by BarryRufer** [comment]
Is there any progress on this? Or do I need to manually edit web/remark.js?

**Comment by codiflow** [comment]
If anybody wants it I translated the whole thing to German.

At the moment I copied all files from inside the docker container (folder "/srv/web") to my host and mapped another volume in my docker-compose.yml like this:

```
volumes:
- ./web:/srv/web
```

So I could modify everything without loosing my changes after a container restart.

If theres a deadline for 1.6 I would contribute my German translation.

**Comment by paskal** [comment]
@codiflow thanks for your work! I think you would be able to add your translation to upstream after #602 will be merged. Please review it if you can, it's a good time to ask questions if something about translations implementation is not clear to you.

**Comment by paskal** [comment]
Translation support is added in #602, I will prepare a PR with documentation on contibuting translations and resolve this issue then.
