### ISSUE TITLE
Documentation: "Complete parameters list" table is cut on 1080p monitor

### ISSUE THREAD

**Issue by vrusinov** [umputun/remark42#1200]
The table in https://remark42.com/docs/configuration/parameters/ does not quite when opened on 1080p monitor (approx. screen width 1900px): 
![Screenshot](https://user-images.githubusercontent.com/711348/146690357-144aff46-6e67-4deb-8dc3-4096e651f988.png) - note how "description" is cut off.

**Comment by paskal** [comment]
CSS to edit: [styles.css](https://github.com/umputun/remark42/blob/master/site/src/styles.css)

**Comment by esvyridov** [comment]
This issue happens because of long strings in environment / command columns which can't be wrapped to the next line. 

It can be fixed by:
- adding a table wrapper with horizontal scrollbar (the table will be scrollable)
- increasing max-width of content wrapper (currently it's 940px) + adding the horizontal scrollbar 
- adding `word-wrap: break-word` to the table (it's not the best solution)
![image](https://user-images.githubusercontent.com/46542370/147156336-f6c041c0-daa2-4ea0-b8fe-d0f5e42949eb.png)

**Comment by paskal** [comment]
For me, a horizontal scrollbar seems to be the only viable solution. Feel free to add it if you know how to do it.

**Comment by vrusinov** [comment]
I agree horizontal scrollbar would be an adequate solution.

> increasing max-width of content wrapper (currently it's 940px)

This also makes sense, I think 940px can be increased without too much harm to readability. It won't be enough to resolve it for all possible resolutions so horizontal scroll-bar still needs to be on.

I don't have ability to contribute now even though it does not sound too complicated. Maybe later if nobody else does. I'll keep watching the issue.
