### ISSUE TITLE
Uninformative tooltip for token input

### ISSUE THREAD

**Issue by dkjb634** [umputun/remark42#1339]
Hello,

It is not clear what a token I should enter in the following tooltip. Would be nice to write something like "Enter the token you received by email"

![image](https://user-images.githubusercontent.com/87329202/165470415-02545164-1ceb-4d0c-bf72-6d1ed55e9238.png)

**Comment by markmonroy** [comment]
Was just coming here to post the same thing. The people who are going to comment on my blog are mostly elderly relatives. The more straightforward the registration process, the better.

By the same token (heh), it would be nice if the token were a short string of numbers instead of a big long hash, which may be difficult to copy on mobile. Or better yet, a link they can click/tap.

**Comment by umputun** [comment]
The long token we sent by email is stateless, i.e. it includes all the info remark42 needs to realize all the auth related fields. Making it shorter won't work in this case. 

Regarding email link - @paskal correct me if wrong, but following the link from email is troublesome because it will loose the state, and we won't be able to navigate to a proper place on UI side. For example, after the login it won't be able to pick the proper comment user answered to, and so on. Probably this can be resolved with some extra params passed and some UI changes, but this doesn't sound easy task to me. Another issue - we don't want to pass it by GET, and I don't know how universal  is POST support in email clients.

**Comment by markmonroy** [comment]
Just following up on this. I feel I may have derailed the topic by bringing up links and shorter strings, but I would love to see @dkjb634 's initial suggestion of descriptive placeholder text, such as "Enter the token you received by email" instead of just "Token." Thanks!

**Comment by dkjb634** [comment]
Completely agree with @markmonroy. It is very confusing. For the first time user feels like "What a Token? I want to add a comment. Where should I get that token, I have no idea."

**Comment by markmonroy** [comment]
I [created a pull request](https://github.com/umputun/remark42/pull/1555) updating the .tsx that defines the placeholder variable. Total amateur here...no idea how to get this change into my docker image, so fingers crossed that this modification works as I hope.
