### ISSUE TITLE
The translation file misses an item

### ISSUE THREAD

**Issue by hao-lee** [umputun/remark42#1362]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/8112645/169656789-27e1e275-8afa-40d4-971a-d2eb074d3582.png">

**Comment by paskal** [comment]
<img width="302" alt="image" src="https://github.com/umputun/remark42/assets/712534/cee32e5b-5f4b-4bf7-9c71-91635f8f18b6">


It's by design, and I'm not sure we want to eliminate it. Here is how it would look like with proper translation:

<img width="303" alt="image" src="https://github.com/umputun/remark42/assets/712534/dbb4d876-0739-4de4-a361-024f2599cc37">

I like the current version more. Resolving this issue, but feel free to add a comment here if you think I'm wrong.
