### ISSUE TITLE
What is the size limit for a comment?

### ISSUE THREAD

**Issue by hostmaster** [umputun/remark42#3]
I tried to make a 2040 chars long comment and I got the error below. If there is an upper limit it would be better to show a more informative message. 

![remark42 demo 2018-05-12 11-27-07](https://user-images.githubusercontent.com/197788/39955476-c6907f4e-55d7-11e8-85e7-384242a81f0e.png)

**Comment by hostmaster** [comment]
Me neither.

**Comment by igoradamenko** [comment]
I still have issue with wrong comment size calculation due to the treatment of EOL. I will try to fix it :-)

**Comment by igoradamenko** [comment]
There is an issue in WHATWG about newline characters and others: whatwg/html#1467. It's an old bug in Webkit, which was fixed in Chrome but in Safari wasn't. 

Honestly, we can implement max length using JS, but I'm sure it would be slower. But what's more important is the fact that it would affect all users of Remark42. I think that this bug with max length in Safari can found maybe tens of users, but all others shouldn't use slow UI because of JS implementation. 

So, I think that we just need to be patient and wait till this bug in Safari is fixed ¯\_(ツ)_/¯.
