### ISSUE TITLE
Enhancement request: edit timer

### ISSUE THREAD

**Issue by RTH10260** [umputun/remark42#408]
After submitting a comment I have like 5 minutes to edit / correct / add.

When I edit the timer can run out when I re-submit after change and I am blocked from further editing.

For the wishlist:
Please reset timer after each edit and re-submit.

**Comment by umputun** [comment]
I'm not sure about this one. In case if you want to have longer edit timeouts, you can be set it to any duration you like or even disable it. Why do we care about resetting the timer?

The reason why we even have this time limit in the first place is to enforce some "comments stability," and this function intended to allow editing for a limited time only to fix typos and things like this. Resetting the timer on any edit will allow virtually unlimited edit window if the user modifies/edits every N-min.

**Comment by paskal** [comment]
Practically something like that opens the potential for unlimited edits for a limited number of users who will exploit it, but ease the life of most of the users.
I say "something like that" because I don't see how this particular thing will help users whos edit is in process. @RTH10260, does system needs to track that they are in process and extend the time each time it is detected? Or you should be aware of this feature and make any edit when you feel that your time is short to buy some more time for "proper" edit? If it's about editing after the first edit, why we don't think about somehow extending the time for the long first edit, not only the ones after the first one?
I don't like any answer to these questions I can think of and support the point of view that just increasing the edit time is the proper and simplest solution to this problem.
