### ISSUE TITLE
Controversy index on touch screen

### ISSUE THREAD

**Issue by vdimir** [umputun/remark42#543]
There is no way to display a controversy in UI on touch devices.

**Comment by paskal** [comment]
Would you be so kind as to add a screenshot with a problem?

**Comment by Vdimir** [comment]
> Would you be so kind as to add a screenshot with a problem?

On desktop cursor should hover on comment's rating to raise controversy info.

<img width="500" alt="Desktop" src="https://user-images.githubusercontent.com/7023786/71964223-364a6e80-320e-11ea-8503-d23bfdfd6e7b.png">


On touch I have tried tap on rating but info doesn't appears. 

<img width="300" alt="Touch" src="https://user-images.githubusercontent.com/7023786/71964210-3185ba80-320e-11ea-895a-60c33dd215ed.PNG">

Even if it will work, tapping on rating may be not very convenient, because it is easy to make missclick.

**Comment by akellbl4** [comment]
As you said, if we make tooltips that will appear by tab it can be difficult to tap in the right place. If we try to place this information permanently It

**Comment by umputun** [comment]
I don't think showing controversy is something important enough to worry about. The sorting by controversy is the primary use case (and it works fine on mobile), but showing controversy value is not something essential.
