### ISSUE TITLE
Incorrect navigation to comments

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#575]
Looks like it works (in most case) with Chrome. However, Safari (Version 13.0.4, MacOS 10.15.2) jumps to the wrong position or doesn't jump at all

example: https://radio-t.com/p/2020/01/18/podcast-685/#remark42__comment-52c578f7-8ff7-4bb2-8106-1d4503131cbf

_Not sure if related to #568_

**Comment by akellbl4** [comment]
It is not related with that PR.
I saw it before. The wrong scroll relates to thread nesting as I see.

**Comment by umputun** [comment]
well, we used to have minor issues with this but currently, it is plain wrong in safari since we added and deployed changes for 1.5

**Comment by akellbl4** [comment]
@umputun I will try to fix it

**Comment by akellbl4** [comment]
I tried to understand what can cause this bug. And wrong navigation meets in other browsers too.
This bug happens because we render only comments that you see and all other comments render like dummy block with height 100px.
When navigation scrolls to the comment it causes render comment above and this comment can be higher than 100px.
For example if we navigate to [the next comment](https://radio-t.com/p/2020/01/18/podcast-685/#remark42__comment-1305ea57-3130-4347-91ad-485fe7bc5b7c) after the comment it will be worst because of previous comment much higher.

**Comment by paskal** [comment]
It seems to be (almost) fixed by now: you get to the correct comment when you click a link from the original message. It's just not on top but in the middle of the screen.
