### ISSUE TITLE
not searchable anymore?

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#585]
_related to #68_

Looks like google switched one of the sites with remark42 to "mobile-first" and in this mode, it doesn't see any comments. This is the preview they show

<img width="383" alt="hfrtb-202001-27134027-zrkk9" src="https://user-images.githubusercontent.com/535880/73207625-a449cd80-410a-11ea-89ee-0a051e870afa.png">

Back in days, I have checked what google renders for search index and seen comments. Not sure why we lost it, maybe due to our rendering?

**Comment by umputun** [comment]
this is the html google webmaster reports. For some reason, it strips comments

[google.html.zip](https://github.com/umputun/remark42/files/4182156/google.html.zip)

**Comment by akellbl4** [comment]
Okay. I realized the reason why comments weren't shown.
It because on mobile we render the only comments what contains in viewport. I will think about what we can do with it.

**Comment by akellbl4** [comment]
I am a bit wrong. We render comments that contain in the viewport on desktop, but I think that google visit site with "special" user-agent and it detects as a desktop.
That's why we render no one comment. Also, in previous time remark had the same behavior but at that time some comments were in viewport.

What we can do?
- Render all comments, but it can cause problems with performance on rendering (I think that's why we have to render only comments what we see in viewport. But I didn't see any lags on my computer when I rendered all comments, maybe we should test it on low-end laptops)
- Render several first comments, but it will not solve our problem completely.

**Comment by umputun** [comment]
@paskal mentioned he was able to search by comments. Can you provide any details pls? Was it for old comments or it worked for you for smth recent?

**Comment by paskal** [comment]
[An example](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fradio-t.com%2Fp%2F+amazon+чехол&oq=site%3Ahttps%3A%2F%2Fradio-t.com%2Fp%2F+amazon+чехол) from Dec 28 2019. Today's comments are still not in search, but April 14 2020 [is here](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fradio-t.com%2Fp%2F+%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9+iPhone+SE+2020).

**Comment by akellbl4** [comment]
@paskal https://webcache.googleusercontent.com/search?q=cache:t0t7v36vyaIJ:https://radio-t.com/p/2019/12/28/podcast-682/+&cd=1&hl=ru&ct=clnk&gl=ru

I think it works for older because it was parsed as desktop version.

**Comment by akellbl4** [comment]
Hm, I was wrong.
[An example ](https://www.google.com/search?ei=JEigXrrfEayHmwWqq5vYCQ&q=site%3Ahttps%3A%2F%2Fradio-t.com%2Fp%2F++%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F+%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE+%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D0%B0&oq=site%3Ahttps%3A%2F%2Fradio-t.com%2Fp%2F++%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F+%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE+%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D0%B0&gs_lcp=CgZwc3ktYWIQA1D_0QFY_9EBYOTUAWgEcAB4AIABL4gBswGSAQE0mAEAoAECoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwi6ga-mk_zoAhWsw6YKHarVBpsQ4dUDCAs&uact=5) with post refered in first message

**Comment by paskal** [comment]
@webkonstantin I tried to figure out if the issue is still present at the moment and saw that comments which are added some time ago are visible on radio-t site, but they are also visible on many different pages because of the side comments section. [Here is the comment](https://radio-t.com/p/2020/10/13/prep-724/#remark42__comment-b1cf564d-606d-49e4-85fd-228ecb449bef) I [searched](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fradio-t.com%2Fp%2F++%22%D0%BA%D0%B8%D1%82%D0%B0%D0%B9%D1%86%D0%B5%D0%B2+%D0%B8+%D0%BA%D0%BE%D1%80%D0%B5%D0%B9%D1%86%D0%B5%D0%B2+%D0%BA%D0%B0%D0%BA+%D0%BC%D0%BE%D0%B6%D0%B5%D1%82.%22) and this is what I saw:

![image](https://user-images.githubusercontent.com/712534/96622937-e525ea00-130a-11eb-86f2-7090e7665559.png)

I think the issue in question doesn't exist at the moment, however, you might want to adjust radio-t site to prevent the side panel from indexing.
