### ISSUE TITLE
Using yarn as package manager for frontend

### ISSUE THREAD

**Issue by akellbl4** [umputun/remark42#676]
I like [yarn](https://yarnpkg.com) because it is faster than npm and has a very good cache strategy and dependency lock. It has all packages from npm because all packages pull/push from/to npm.

Migration to this package manager won't take lots of time especially because we already update our dependencies and any docker images with node already has preinstalled yarn.

If you want to know the advantages of yarn it is easy to found a huge amount of articles "why yarn better than npm" and "why you should switch to yarn" and no one "why npm better than yarn".

**Comment by ttys3** [comment]
it' s 2020 now ,  I am afraid yarn is not as years ago faster than npm

**Comment by paskal** [comment]
I think the only fair way to decide is to list things which are better in yarn than in npm and vice versa better in npm than yarn _for this particular project_.
Then you and other frontend-savvy people in the project will be able to estimate if improvements for the switch overweight the complexity of the switch plus cost of using a less popular tool and other related costs.

**Comment by ttys3** [comment]
I used to think that yarn would be faster than npm. and I've been using yarn for npm replacement for years.

But last year I saw an article([Should you choose npm or yarn?](https://javascript.christmas/2019/10) ) about yarn and npm, which make me rethink, should I switch from yarn to npm ?

below is the content:

Every team has to make various decisions before, and during, the development of a digital product. One of these usually involves yarn, npm or another tool to build and package javascript code. Some developers have a burning desire to go in a certain direction, and sometimes they end up spending a considerable amount of time trying to make decisions that in fact will have little impact in their everyday life.

To understand why this is an interesting decision to make in the first place, we need to have a look at the history of package management in javascript.

Pre npm: frontend dependencies are downloaded manually and stored into the repositories 📁
2010: npm is released and supports nodejs 📦
2012: npm usage is dramatically increasing - primarily due to Browserifys browser support 🎉
2012: npm get a competitor, bower, that entirely supports browsers 💻
2012-2016: The number of dependencies for frontend projects increases exponentially 🤯
2012-2016: Building and installing frontend applications becomes slower and slower 🐢
2012-2016: An infinite amount of (duplicated) dependencies are stored in nested folders within the magic node_modules ☢️
2012-2016: rm -rf node_modules the most frequently used command as a frontend developer..? 🗑
2015: bower lose the battle against npm 💀
2015: node_modules are changed to a (more) flatten file structure! 🕸
2016: left-pad becomes the worldwide news of the day 👈
2016: yarn is released 🚀

Supports both npm and bower repositories
yarn.lock locks installed versions and provide deterministic dependencies. No more rm -rf node_modules!
yarn install spend about half the time versus npm install (without using cache)
Caching and offline mode enables build processes to consume nearly no time
**2016: npm releases shrinkwrap 🧯**

An attempt to handle dependency locking
Unfortunately, several errors and promising more than it could manage - the reputation of the tool became poor
2017: npm 5 is released 🔓

package-lock.json is their new tool, shrinkwrap is put aside
**package-lock.json take on the fight against yarns lock file**
2018: npm ci is released 🛬

> Build code using package-lock.json directly
> No expensive security and version analyses on the dependencies
**Build time is drastically reduced on the build server!**

2018: npm 6 is released 👮‍♀️

npm check security vulnerabilities for dependencies to be installed
No significant variance in build time between yarn and npm
2019: tink is in beta mode 🦋

Avoid using node_modules and rather have one file with hashes for each dependency in the project
Not yet production-ready
...

**Comment by akellbl4** [comment]
@ttys3 thanks for the article, I didn't see it before. I've made a few benchmarks and yarn still faster, but not significant.
I started using `yarn` right after its release and I'm happy with it. But as you have said maybe now there are not so many reasons to change npm.
I wanted to hear another opinion about it and I got it :)

**Comment by ttys3** [comment]
@akellbl4 yes, I'm also a `yarn fans`, 
I always use `yarn` and even replace the package manager with `yarn` when I cloned a frontend project which uses `npm`.
But I'm glad that I saw the article and the improvement of `npm`
