### ISSUE TITLE
Height of iframe changes on page scroll

### ISSUE THREAD

**Issue by leem32** [umputun/remark42#702]
When there are comments I notice the iframe height changes on page scroll.
The more comments on the page the more the iframe height changes.

Why does this happen?

I ask because it's causing me issues with matching up left/right column height.

EDIT: Just wanted to add that I can easily fix my equal column height issue with a `scroll` event listener, but was just wondering why it happens.

**Comment by akellbl4** [comment]
It happens because we prerender only dummy blocks for comments. And actually render comments by scroll when it appears in the viewport and it causes a change of iframe height.
It was made for performance optimization of the first rendering.

If you can provide the link to your site I could try to help with your issue.

**Comment by leem32** [comment]
OK, thanks. I've already fixed the issue myself so no need.
I thought it was probably a lazy loading type thing anyway, but thanks for the confirmation :)
