### ISSUE TITLE
Don't bind to host port by default?

### ISSUE THREAD

**Issue by ivastly** [umputun/remark42#733]
In my experience, remark42 always spoils the host by binding to host's port (following `REMARK_PORT` variable). Is it possible to avoid this behaviour? By letting the user choose the way for remark42 to interact with the outer world, instead of dictating this from inside the container. Something like nginx does it, for example.

For intance, in my setup I use nginx-proxy listening on 80 and 443 and jrcs/letsencrypt-nginx-proxy-companion for SSL. I don't want remark42 to listen on host at all. But it tries to bind anyway. So I have to workaround this by giving remark42 a random, not used port for it to bind to. Not good at all, in terms of security as well.

Let me know what do you think, thanks for a great product!

**Comment by umputun** [comment]
I'm not sure what you mean. Sounds like you are talking about dockerized remark42, right? If this is the case what "dictating this from inside the container" is? Remark42 has to listen on some port and uses has full control of what port to use. In addition, user can control (on docker level) how this port exposed (or not). 

I'm not really sure what you mean by "I don't want remark42 to listen on host at all". If this is a stand-alone version it has to listen on some of host's port because this is how other parts (ui, proxy, and so on) communicate with remark42. If this is a dockerized version and your proxy listens on 80/443 it has to have a way to reach remark42 via host or bridge, depends on how you run it.

I also puzzled by the workaround you mentioned - " giving remark42 a random, not used port for it to bind to". On what level? If this is about docker's port - you don't have to expose any docker ports. Pls note - the provided [docker-compose.yml example](https://github.com/umputun/remark42/blob/master/docker-compose.yml) has port mapping directive commented.

**Comment by umputun** [comment]
and one more thing got me confused  - "Not good at all, in terms of security as well.". The system is supposed to be publically accessible, directly, or behind the proxy. What is the security risk you have in mind?

**Comment by ivastly** [comment]
Thank you for detailed reply, I will provide a clear example of what I mean soon. Sorry for confusion.

**Comment by ivastly** [comment]
found out that I just got it all wrong during the first try, sorry for false positive. Thanks again for a great product!

**Comment by ivastly** [comment]
discussed in podcast at https://radio-t.com/p/2020/06/13/podcast-706/ 0:38:45 (Russian)
