### ISSUE TITLE
What paths can be cached ?

### ISSUE THREAD

**Issue by George3d6** [umputun/remark42#743]
If I use remark42 behind some sort of reverse proxy (e.g. nginx) I might want to add some sort of timed cache to its answers for certain paths, the script, the actual comments (shouldn't be that bad to cache them with a quick refresh, e.g. every 10 seconds) and potentially others (?).

What are the url paths one would need to cache for this to happen (i.e. something like `{host:port}/path/to/a/static/file.js`)

**Comment by umputun** [comment]
remark42 already does caching on the backend side. It is not as simple as "cache some url response" because invalidation logic is not trivial. Pls note - it caches some sort of "blobs", i.e. complete response. You may try some performance testing and could see a cold call taking 20ms or so and the next call will be completed in microseconds.

Do you have any real problem with the current caching and there is a reason to add another layer on the nginx side? In case if you really have such a need, see calls around `cache.NewKey` in rest/api package, it may give you an idea what and how to cache

**Comment by George3d6** [comment]
Ah, I did not actually observe the flag / mentions of it already having a cache, for my usecase a mem cache is enough, the nginx caching might shave of some microseconds but it'd be superfluous. Sorry for the bother 😅
