### ISSUE TITLE
Possible bug: same email considered as different user

### ISSUE THREAD

**Issue by kokizzu** [umputun/remark42#748]
Tried login with google, comment, logout, tried comment with github with same email, comment

both user have 2 different avatar link '__') so possibly it was considered as 2 different user?
`google_1f5e355cfa498713a3ddb885b36170e0423598fa`
and 
`github_340109fdb1bd29a222d2b9e7a30523543bf619e8`

**Comment by umputun** [comment]
Each social provider is different and remark42 doesn't consolidate user info by design. In fact, it doesn't even keep the user's email unless requested directly for notifications. So, it has no clue if the user logged in via github/google/ms/direct email/etc the same person.

This is not a bug but a deliberate decision.
