### ISSUE TITLE
Delete anonymous comments

### ISSUE THREAD

**Issue by ssubara** [umputun/remark42#774]
When I try to delete posted comment as anonymous in first 5 min with API /api/v1/comment/{id}?site=site-id&url=post-url I have body response 'Unauthorized'? How I can delete comments with API if they posted from anonymous user?
Thanks

**Comment by umputun** [comment]
anonymous users limited by design and can't perform some actions, however, edit/remove allowed. You can see it live on https://remark42.com/demo/ (login as anonymous) and try to create/edit/delete. As you will see - it works just fine.

I don't know what exactly your case because based on the description I have no idea if you passed the auth header or worked with auth cookies, but generally speaking there is nothing special here. The same way you delete non-anonymous should work for anonymous users

**Comment by ssubara** [comment]
I trying to delete comment with API from Postman :( with URL structure "api/v1/comment/{id}?site=site-id&url=post-url" 
I tried to pass tokens with header but on every call I have 'Unauthorized'.
Can you please give me example of call. Thanks

**Comment by umputun** [comment]
well, this is the correct call. I guess you do PUT and send {"delete": true} in the body.

How exactly you obtain the token? Are you sure you send the valid one, i.e. the same used to make the original comment?

To see real-life examples of calls you can turn on Inspector/Dev tools in your browser and check what https://remark42.com/demo/  sends. This is an example, I just did delete of my anonymous comment:

<img width="1045" alt="kju41-202009-14121656-wrrgn" src="https://user-images.githubusercontent.com/535880/93117626-bde15a80-f684-11ea-8dad-d7a3b0fdeca0.png">

If you call it with `X-JWT` header, pass the token here instead of the cookie

Also, see a bunch of examples [here](https://github.com/umputun/remark42/blob/master/backend/remark.rest). Hopefully postman can import such .rest/.http file

**Comment by ssubara** [comment]
Thanks
