### ISSUE TITLE
-1 comment

### ISSUE THREAD

**Issue by shalugin** [umputun/remark42#776]
![Screenshot_20200914_074141_com yandex browser](https://user-images.githubusercontent.com/1784377/93044675-0df8f680-f65e-11ea-9c14-3d74a66dc47d.jpg)

**Comment by grigoriy-orlov** [comment]
Steps to reproduce:
* add single comment (head comment)
* add subcomments
* remove head comment

**Comment by paskal** [comment]
I can't reproduce this one locally.
@webkonstantin can you please help me figure out where the number on radio-t site comes from precisely?

**Comment by paskal** [comment]
radio-t site seems to be using `/api/v1/counts` [endpoint](890d7154e777d0673defcd11db3ef792473d68c9), I can't reproduce the problem locally, as I always get precise number of comments.

If someone will reproduce it on a clear dev instance of remark42 I'll be able to fix it. To do so download the repository and run `make rundev` in it, and then head to http://127.0.0.1:8080/web/, you'll see post count in the top right of the page.

**Comment by umputun** [comment]
The fix in #808 confirmed what I observed - dbl-delete of comments. This happened due to UI-related issues in the admin part. As I blocked some spam users permanently I thought nothing happened and repeated the action. Permanent blocking in fact a multiple deletes and this is how we got it.

The reason why blocking action felt like "nothing happens" is the async nature of it and luck of any visual confirmation.
