### ISSUE TITLE
Custom auth and site ID

### ISSUE THREAD

**Issue by CodeWithOz** [umputun/remark42#779]
Nice library!

I'm considering using this in a cordova app, which means I won't be able to have separate site urls for comment sections. Will it be a lot of work to have the backend create comment sections based on info that's supplied when creating the first post? I'm thinking of generating a unique site ID everywhere that I need a different comment section, but I want to be sure this is okay how this library works.

Also, I have my own auth in the app, so I don't want to include third-party auth. Are there any concerns/pitfalls I should be aware of if I want to replace the auth with my own auth?

**Comment by CodeWithOz** [comment]
The auth question seems related to #752, which isn't resolved yet.

**Comment by CodeWithOz** [comment]
More details on what we're considering, we'd appreciate any input you can provide:
- Using a proxy server (or load balancer) so that we can have urls for each thread
- To maintain different threads, we're considering two options:
  - Adding logic to proxy server such that it creates unique names/IDs for threads (using unique and fixed info about each thread when it's created), and repurposing some of the source code of Remark to use those unique names/IDs instead of expecting different site urls/IDs
  - Using the proxy server url as a base url and generating unique paths that are appended to the base url in order to generate the site IDs that Remark normally expects.
    - Is this second option okay or is it an anti-pattern or does it have any pitfalls? Every comment thread would be under one url just with a different path eg. https://proxy.server/id-one and https://proxy.server/id-two.
- Concerns about federation on multiple servers: basically this would affect retrieval of threads, so when you search for the reply thread on one message it knows what server to fetch it on without a middle layer. Would we need to host the backend on each of the multiple servers?

Thanks for your work!

**Comment by umputun** [comment]
I don't really get what you are trying to achieve. Also, you called it "library" a few times, but in fact, this is a complete system with the backend and frontend working together. 

You mentioned "cordova app, which means I won't be able to have separate site urls for comment sections". I have no clue what it means, but nothing prevents you from using as many site ids as you need. 

> Will it be a lot of work to have the backend create comment sections based on info that's supplied when creating the first post?

Again, I don't understand the context, but this is how it already works. All comments contain references to the "parent" URL as well as site-id, see  https://github.com/umputun/remark42/blob/master/backend/app/store/comment.go#L34

> Also, I have my own auth in the app, so I don't want to include third-party auth. Are there any concerns/pitfalls I should be aware of if I want to replace the auth with my own auth?

If you will maintain your fork of the backend, replacing auth should be doable and straightforward. Our auth library supports custom providers. For more details, see https://github.com/go-pkgz/auth

Regarding your second comment: generally, the backend doesn't care about what URL you pass and if this was the same host or not. All it needs is to keep Locator properly referencing comments to the post. From the backend point of view, Locator is just a pair of strings. It doesn't matter where this pair is coming from. For our web app, this is the page's URL but it can be anything else for other frontends, any ID you make as long as it identify the parent "thing" (post, article, or anything else you want comments to be attached to).

> Concerns about federation on multiple servers

You may access the same instance hosting remark42 backend from multiple frontends servers. If you need multiple backend servers you will have to provide an alternative store and cache implementations supporting shared access.

_I'm not sure if my answers helped, but because I don't understand your use case it is hard to figure what you meant._

**Comment by CodeWithOz** [comment]
@umputun thanks for the response! Sorry I didn't provide enough background, and pardon my terminology, this is indeed a full backend and frontend system :clap: :rocket: .

[Cordova](https://cordova.apache.org/) is a platform for making hybrid apps that rely on a [webview](https://developer.android.com/guide/webapps/webview) (this is for Android, iOS has its own), but one of the effects of this setup is that requests originating from the app may not have a valid origin URL, so I was worried about that potentially not playing well with the backend. Your explanation still answers my question though since you've said the site ID can be any string that references the post. :+1: 

For auth I'll take a closer look at the auth library, thanks :+1: .

And thanks for clarifying with the comment on multiple backend servers.

**Comment by CodeWithOz** [comment]
@umputun quick question. Do anonymous users ever get deleted from the user database? I can see that the same anonymous user gets logged in if I login with a previously used username. But is there ever a point at which re-using a username would create a brand new user?

**Comment by umputun** [comment]
> Do anonymous users ever get deleted from the user database? 

The never get written to any database. All it does for such users is making user id based on the entered name. This is [the code](https://github.com/umputun/remark42/blob/master/backend/app/cmd/server.go#L760) on remark42 side and it leverages passwordless [direct provider](https://github.com/go-pkgz/auth/blob/master/provider/direct.go#L96) from go-pkgz/auth library. 

>  But is there ever a point at which re-using a username would create a brand new user?

No. In theory, I could randomize ID, so user "blah" will get a different ID (and avatar) every time he logged in as "blah", but I don't see why this will be any better. The only semi-valid reason for doing this will be navigation to user's comments, as it will show only comment this particular anonymous made, but ever way it won't be permanent (the token will expire eventually and the user will have to relogin). Also, it is kind of defeats the primary goal of having anonymous users because those "linked" users will lose some part of anonymity.

**Comment by CodeWithOz** [comment]
@umputun thanks for clarifying. To be clear, the current behavior works for me because I want the same user ID to be re-generated for the same username. So I wasn't suggesting that I wanted a change to that behavior.

> All it does for such users is making user id based on the entered name.

Based on this, do you think it will be a good idea to save other metadata for the anonymous user in my own database? So for instance if I want to keep metadata on the user who logged in with "user12345", it should be safe to expect that remark42 will always return the same user ID and therefore I can associate other metadata with that user ID, right? This is what is I understood from what you said, but I want to be sure it's correct.

**Comment by umputun** [comment]
> it should be safe to expect that remark42 will always return the same user ID

Not really. The "always" part is relevant for the current implementation only and sure - some particular (current master or the current release version) version will always work like you described. However, this behavior is not a part of the public API but just an internal implementation detail. Such details may be changed for whatever reasons. 

Pls note - the assumption you made by trying to save meta for "user12345" may be incorrect because, technically, nothing prevents another anonymous user to login with the same name. Even if your app handles it by assigning different names somehow, the rest API is still open and some user may invoke a direct http request against this API
